version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: neovision
      POSTGRES_USER: neovision
      POSTGRES_PASSWORD: neovision123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neovision"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB for document storage
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: neovision
      MONGO_INITDB_ROOT_PASSWORD: neovision123
      MONGO_INITDB_DATABASE: neovision
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.full
    ports:
      - "8001:8000"  # Host port 8001 → Container port 8000
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://neovision:neovision123@postgres:5432/neovision
      - MONGODB_URL=mongodb://neovision:neovision123@mongodb:27017/neovision
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/backend
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/temp:/app/backend/temp
      - ./backend/logs:/app/backend/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker for background tasks
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.full
    command: ["celery", "-A", "backend.celery_app", "worker", "--loglevel=info"]
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://neovision:neovision123@postgres:5432/neovision
      - MONGODB_URL=mongodb://neovision:neovision123@mongodb:27017/neovision
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/backend
    depends_on:
      - postgres
      - mongodb
      - redis
      - backend
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/temp:/app/backend/temp
      - ./backend/logs:/app/backend/logs

  # Celery Beat for scheduled tasks
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.full
    command: ["celery", "-A", "backend.celery_app", "beat", "--loglevel=info"]
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://neovision:neovision123@postgres:5432/neovision
      - MONGODB_URL=mongodb://neovision:neovision123@mongodb:27017/neovision
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/backend
    depends_on:
      - postgres
      - mongodb
      - redis
      - backend
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/temp:/app/backend/temp
      - ./backend/logs:/app/backend/logs

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
