version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: multi-agent-backend
    ports:
      - "8002:8000"  # Changed from 8000 to 8002
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yourpassword
      - PINECONE_API_KEY=${PINECONE_API_KEY:-}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - neo4j
    networks:
      - agent_network
    volumes:
      - ./data/backend:/app/data
    restart: unless-stopped

  # Frontend Application
  app:
    build: .
    container_name: multi-agent-app
    ports:
      - "8086:80"  # Changed from 8085 to 8086
    depends_on:
      - backend
      - neo4j
      - ollama
    networks:
      - agent_network

  # Neo4j Database
  neo4j:
    image: neo4j:5.15
    container_name: multi-agent-neo4j
    ports:
      - "7475:7474"  # Changed from 7474 to 7475 (HTTP)
      - "7688:7687"  # Changed from 7687 to 7688 (Bolt)
    environment:
      - NEO4J_AUTH=neo4j/yourpassword
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./backups:/backups
    networks:
      - agent_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Ollama for Local LLM (Optional - can be commented out if you have existing Ollama)
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: multi-agent-ollama
  #   ports:
  #     - "11435:11434"  # Changed from 11434 to 11435
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - agent_network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  # Local SQLite for fallback/caching
  sqlite:
    image: keinos/sqlite3:latest
    container_name: multi-agent-sqlite
    volumes:
      - ./data/sqlite:/data
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  # ollama_data:  # Commented out since Ollama is optional
